/* ----- Chord database -----
   Única fuente de verdad de acordes para el workspace "acordes":
   la consume el buscador web (reference/chord-finder.html) y la extensión de Chrome.

   Cobertura: para las 12 fundamentales — mayor, menor, 7, m7, maj7, 6, maj9, sus2, sus4 —
   más dim7 (los 12), aug, slash y tensiones comunes. Posiciones abiertas donde
   existen; formas movibles con cejilla para el resto.

   Voicings notation per svguitar: fingers = [[string, fret|'x'|'o', fingerLabel?], ...]
   Strings: 1 = high E (mi agudo), 6 = low E (mi grave). Frets count from nut.
   `position` (opcional, default 1) = traste más bajo mostrado, para formas subidas.
   `barres` (opcional) = [{ fromString, toString, fret }, ...] para cejillas.
   `families` is used by filter pills. `aliases` powers search. */

window.CHORDS = [
  // ----- MAYORES -----
  { name: 'C', families: ['major'], aliases: ['CM','Cmaj'],
    notes: 'C E G',
    fingers: [[6,'x'],[5,3,'3'],[4,2,'2'],[3,'o'],[2,1,'1'],[1,'o']] },
  { name: 'D', families: ['major'], aliases: ['DM','Dmaj'],
    notes: 'D A D F♯',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,2,'1'],[2,3,'3'],[1,2,'2']] },
  { name: 'E', families: ['major'], aliases: ['EM','Emaj'],
    notes: 'E B E G♯ B E',
    fingers: [[6,'o'],[5,2,'2'],[4,2,'3'],[3,1,'1'],[2,'o'],[1,'o']] },
  { name: 'G', families: ['major'], aliases: ['GM','Gmaj'],
    notes: 'G B D G B G',
    fingers: [[6,3,'2'],[5,2,'1'],[4,'o'],[3,'o'],[2,3,'3'],[1,3,'4']] },
  { name: 'A', families: ['major'], aliases: ['AM','Amaj'],
    notes: 'A E A C♯ E',
    fingers: [[6,'x'],[5,'o'],[4,2,'1'],[3,2,'2'],[2,2,'3'],[1,'o']] },
  { name: 'F', families: ['major'], aliases: [],
    notes: 'F C F A C F', position: 1, barres: [{fromString:6,toString:1,fret:1}],
    fingers: [[5,3,'3'],[4,3,'4'],[3,2,'2']] },
  { name: 'F♯', families: ['major'], aliases: ['G♭'],
    notes: 'F♯ C♯ F♯ A♯ C♯ F♯', position: 1, barres: [{fromString:6,toString:1,fret:2}],
    fingers: [[5,4,'3'],[4,4,'4'],[3,3,'2']] },
  { name: 'A♭', families: ['major'], aliases: ['G♯'],
    notes: 'A♭ E♭ A♭ C E♭ A♭', position: 4, barres: [{fromString:6,toString:1,fret:4}],
    fingers: [[5,6,'3'],[4,6,'4'],[3,5,'2']] },
  { name: 'B♭', families: ['major'], aliases: ['A♯'],
    notes: 'B♭ F B♭ D F', position: 1, barres: [{fromString:5,toString:1,fret:1}],
    fingers: [[6,'x'],[4,3,'2'],[3,3,'3'],[2,3,'4']] },
  { name: 'B', families: ['major'], aliases: [],
    notes: 'B F♯ B D♯ F♯', position: 1, barres: [{fromString:5,toString:1,fret:2}],
    fingers: [[6,'x'],[4,4,'2'],[3,4,'3'],[2,4,'4']] },
  { name: 'D♭', families: ['major'], aliases: ['C♯'],
    notes: 'D♭ A♭ D♭ F A♭', position: 4, barres: [{fromString:5,toString:1,fret:4}],
    fingers: [[6,'x'],[4,6,'2'],[3,6,'3'],[2,6,'4']] },
  { name: 'E♭', families: ['major'], aliases: ['D♯'],
    notes: 'E♭ B♭ E♭ G B♭', position: 6, barres: [{fromString:5,toString:1,fret:6}],
    fingers: [[6,'x'],[4,8,'2'],[3,8,'3'],[2,8,'4']] },

  // ----- MENORES -----
  { name: 'Am', families: ['minor'], aliases: ['Amin','A-'],
    notes: 'A E A C E',
    fingers: [[6,'x'],[5,'o'],[4,2,'2'],[3,2,'3'],[2,1,'1'],[1,'o']] },
  { name: 'Dm', families: ['minor'], aliases: ['Dmin','D-'],
    notes: 'D A D F',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,2,'2'],[2,3,'3'],[1,1,'1']] },
  { name: 'Em', families: ['minor'], aliases: ['Emin','E-'],
    notes: 'E B E G B E',
    fingers: [[6,'o'],[5,2,'2'],[4,2,'3'],[3,'o'],[2,'o'],[1,'o']] },
  { name: 'Fm', families: ['minor'], aliases: [],
    notes: 'F C F G♯ C F', position: 1, barres: [{fromString:6,toString:1,fret:1}],
    fingers: [[5,3,'2'],[4,3,'3']] },
  { name: 'F♯m', families: ['minor'], aliases: ['G♭m'],
    notes: 'F♯ C♯ F♯ A C♯ F♯', position: 1, barres: [{fromString:6,toString:1,fret:2}],
    fingers: [[5,4,'2'],[4,4,'3']] },
  { name: 'Gm', families: ['minor'], aliases: [],
    notes: 'G D G A♯ D G', position: 1, barres: [{fromString:6,toString:1,fret:3}],
    fingers: [[5,5,'2'],[4,5,'3']] },
  { name: 'G♯m', families: ['minor'], aliases: ['A♭m'],
    notes: 'G♯ D♯ G♯ B D♯ G♯', position: 4, barres: [{fromString:6,toString:1,fret:4}],
    fingers: [[5,6,'2'],[4,6,'3']] },
  { name: 'B♭m', families: ['minor'], aliases: ['A♯m'],
    notes: 'B♭ F B♭ D♭ F', position: 1, barres: [{fromString:5,toString:1,fret:1}],
    fingers: [[6,'x'],[4,3,'3'],[3,3,'4'],[2,2,'2']] },
  { name: 'Bm', families: ['minor'], aliases: [],
    notes: 'B F♯ B D F♯', position: 1, barres: [{fromString:5,toString:1,fret:2}],
    fingers: [[6,'x'],[4,4,'3'],[3,4,'4'],[2,3,'2']] },
  { name: 'C♯m', families: ['minor'], aliases: ['D♭m'],
    notes: 'C♯ G♯ C♯ E G♯', position: 4, barres: [{fromString:5,toString:1,fret:4}],
    fingers: [[6,'x'],[4,6,'3'],[3,6,'4'],[2,5,'2']] },
  { name: 'E♭m', families: ['minor'], aliases: ['D♯m'],
    notes: 'E♭ B♭ E♭ G♭ B♭', position: 6, barres: [{fromString:5,toString:1,fret:6}],
    fingers: [[6,'x'],[4,8,'3'],[3,8,'4'],[2,7,'2']] },
  { name: 'Cm', families: ['minor'], aliases: [],
    notes: 'C G C D♯ G', position: 1, barres: [{fromString:5,toString:1,fret:3}],
    fingers: [[6,'x'],[4,5,'3'],[3,5,'4'],[2,4,'2']] },

  // ----- DOMINANTES 7 (7) -----
  { name: 'A7', families: ['dom7'], aliases: [],
    notes: 'A E G C♯ E',
    fingers: [[6,'x'],[5,'o'],[4,2,'2'],[3,'o'],[2,2,'3'],[1,'o']] },
  { name: 'B7', families: ['dom7'], aliases: [],
    notes: 'B D♯ A B F♯',
    fingers: [[6,'x'],[5,2,'2'],[4,1,'1'],[3,2,'3'],[2,'o'],[1,2,'4']] },
  { name: 'C7', families: ['dom7'], aliases: [],
    notes: 'C E B♭ C E',
    fingers: [[6,'x'],[5,3,'3'],[4,2,'2'],[3,3,'4'],[2,1,'1'],[1,'o']] },
  { name: 'D7', families: ['dom7'], aliases: [],
    notes: 'D A C F♯',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,2,'2'],[2,1,'1'],[1,2,'3']] },
  { name: 'E7', families: ['dom7'], aliases: [],
    notes: 'E B D G♯ B E',
    fingers: [[6,'o'],[5,2,'2'],[4,'o'],[3,1,'1'],[2,'o'],[1,'o']] },
  { name: 'G7', families: ['dom7'], aliases: [],
    notes: 'G B D G B F',
    fingers: [[6,3,'3'],[5,2,'2'],[4,'o'],[3,'o'],[2,'o'],[1,1,'1']] },
  { name: 'F7', families: ['dom7'], aliases: [],
    notes: 'F C D♯ A C F', position: 1, barres: [{fromString:6,toString:1,fret:1}],
    fingers: [[5,3,'3'],[3,2,'2']] },
  { name: 'F♯7', families: ['dom7'], aliases: ['G♭7'],
    notes: 'F♯ C♯ E A♯ C♯ F♯', position: 1, barres: [{fromString:6,toString:1,fret:2}],
    fingers: [[5,4,'3'],[3,3,'2']] },
  { name: 'A♭7', families: ['dom7'], aliases: ['G♯7'],
    notes: 'A♭ E♭ G♭ C E♭ A♭', position: 4, barres: [{fromString:6,toString:1,fret:4}],
    fingers: [[5,6,'3'],[3,5,'2']] },
  { name: 'B♭7', families: ['dom7'], aliases: ['A♯7'],
    notes: 'B♭ F A♭ D F', position: 1, barres: [{fromString:5,toString:1,fret:1}],
    fingers: [[6,'x'],[4,3,'2'],[2,3,'3']] },
  { name: 'D♭7', families: ['dom7'], aliases: ['C♯7'],
    notes: 'D♭ A♭ B F A♭', position: 4, barres: [{fromString:5,toString:1,fret:4}],
    fingers: [[6,'x'],[4,6,'2'],[2,6,'3']] },
  { name: 'E♭7', families: ['dom7'], aliases: ['D♯7'],
    notes: 'E♭ B♭ D♭ G B♭', position: 6, barres: [{fromString:5,toString:1,fret:6}],
    fingers: [[6,'x'],[4,8,'2'],[2,8,'3']] },

  // ----- MENORES 7 (m7) -----
  { name: 'Am7', families: ['m7'], aliases: ['A-7'],
    notes: 'A E G C E',
    fingers: [[6,'x'],[5,'o'],[4,2,'2'],[3,'o'],[2,1,'1'],[1,'o']] },
  { name: 'Dm7', families: ['m7'], aliases: ['D-7'],
    notes: 'D A C F',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,2,'2'],[2,1,'1'],[1,1,'1']] },
  { name: 'Em7', families: ['m7'], aliases: ['E-7'],
    notes: 'E B D G B E',
    fingers: [[6,'o'],[5,2,'2'],[4,'o'],[3,'o'],[2,'o'],[1,'o']] },
  { name: 'Fm7', families: ['m7'], aliases: [],
    notes: 'F C D♯ G♯ C F', position: 1, barres: [{fromString:6,toString:1,fret:1}],
    fingers: [[5,3,'2']] },
  { name: 'F♯m7', families: ['m7'], aliases: ['G♭m7'],
    notes: 'F♯ C♯ E A C♯ F♯', position: 1, barres: [{fromString:6,toString:1,fret:2}],
    fingers: [[5,4,'2']] },
  { name: 'Gm7', families: ['m7'], aliases: [],
    notes: 'G D F A♯ D G', position: 1, barres: [{fromString:6,toString:1,fret:3}],
    fingers: [[5,5,'2']] },
  { name: 'G♯m7', families: ['m7'], aliases: ['A♭m7'],
    notes: 'G♯ D♯ F♯ B D♯ G♯', position: 4, barres: [{fromString:6,toString:1,fret:4}],
    fingers: [[5,6,'2']] },
  { name: 'B♭m7', families: ['m7'], aliases: ['A♯m7'],
    notes: 'B♭ F A♭ D♭ F', position: 1, barres: [{fromString:5,toString:1,fret:1}],
    fingers: [[6,'x'],[4,3,'3'],[2,2,'2']] },
  { name: 'Bm7', families: ['m7'], aliases: [],
    notes: 'B F♯ A D F♯', position: 1, barres: [{fromString:5,toString:1,fret:2}],
    fingers: [[6,'x'],[4,4,'3'],[2,3,'2']] },
  { name: 'C♯m7', families: ['m7'], aliases: ['D♭m7'],
    notes: 'C♯ G♯ B E G♯', position: 4, barres: [{fromString:5,toString:1,fret:4}],
    fingers: [[6,'x'],[4,6,'3'],[2,5,'2']] },
  { name: 'E♭m7', families: ['m7'], aliases: ['D♯m7'],
    notes: 'E♭ B♭ D♭ G♭ B♭', position: 6, barres: [{fromString:5,toString:1,fret:6}],
    fingers: [[6,'x'],[4,8,'3'],[2,7,'2']] },
  { name: 'Cm7', families: ['m7'], aliases: [],
    notes: 'C G A♯ D♯ G', position: 1, barres: [{fromString:5,toString:1,fret:3}],
    fingers: [[6,'x'],[4,5,'3'],[2,4,'2']] },

  // ----- MAYORES 7 (maj7) -----
  { name: 'Cmaj7', families: ['maj7'], aliases: ['CM7','CΔ7','CΔ'],
    notes: 'C E G B E',
    fingers: [[6,'x'],[5,3,'3'],[4,2,'2'],[3,'o'],[2,'o'],[1,'o']] },
  { name: 'Fmaj7', families: ['maj7'], aliases: ['FM7','FΔ7'],
    notes: 'F A C E',
    fingers: [[6,'x'],[5,'x'],[4,3,'3'],[3,2,'2'],[2,1,'1'],[1,'o']] },
  { name: 'Gmaj7', families: ['maj7'], aliases: ['GM7','GΔ7'],
    notes: 'G B D F♯ B',
    fingers: [[6,3,'3'],[5,2,'2'],[4,'o'],[3,'o'],[2,'o'],[1,2,'1']] },
  { name: 'F♯maj7', families: ['maj7'], aliases: ['G♭maj7'],
    notes: 'F♯ C♯ F A♯ C♯ F♯', position: 1, barres: [{fromString:6,toString:1,fret:2}],
    fingers: [[5,4,'4'],[4,3,'2'],[3,3,'3']] },
  { name: 'A♭maj7', families: ['maj7'], aliases: ['G♯maj7'],
    notes: 'A♭ E♭ G C E♭ A♭', position: 4, barres: [{fromString:6,toString:1,fret:4}],
    fingers: [[5,6,'4'],[4,5,'2'],[3,5,'3']] },
  { name: 'B♭maj7', families: ['maj7'], aliases: ['A♯maj7'],
    notes: 'B♭ F A D F', position: 1, barres: [{fromString:5,toString:1,fret:1}],
    fingers: [[6,'x'],[4,3,'3'],[3,2,'2'],[2,3,'4']] },
  { name: 'Bmaj7', families: ['maj7'], aliases: [],
    notes: 'B F♯ A♯ D♯ F♯', position: 1, barres: [{fromString:5,toString:1,fret:2}],
    fingers: [[6,'x'],[4,4,'3'],[3,3,'2'],[2,4,'4']] },
  { name: 'D♭maj7', families: ['maj7'], aliases: ['C♯maj7'],
    notes: 'D♭ A♭ C F A♭', position: 4, barres: [{fromString:5,toString:1,fret:4}],
    fingers: [[6,'x'],[4,6,'3'],[3,5,'2'],[2,6,'4']] },
  { name: 'E♭maj7', families: ['maj7'], aliases: ['D♯maj7'],
    notes: 'E♭ B♭ D G B♭', position: 6, barres: [{fromString:5,toString:1,fret:6}],
    fingers: [[6,'x'],[4,8,'3'],[3,7,'2'],[2,8,'4']] },
  { name: 'Amaj7', families: ['maj7'], aliases: ['AM7','AΔ7'],
    notes: 'A E G♯ C♯ E',
    fingers: [[6,'x'],[5,'o'],[4,2,'2'],[3,1,'1'],[2,2,'3'],[1,'o']] },
  { name: 'Dmaj7', families: ['maj7'], aliases: ['DM7','DΔ7'],
    notes: 'D A C♯ F♯',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,2,'1'],[2,2,'2'],[1,2,'3']] },
  { name: 'Emaj7', families: ['maj7'], aliases: ['EM7','EΔ7'],
    notes: 'E B D♯ G♯ B E',
    fingers: [[6,'o'],[5,2,'2'],[4,1,'1'],[3,1,'1'],[2,'o'],[1,'o']] },

  // ----- SUS (sus2 / sus4) -----
  { name: 'Dsus2', families: ['sus'], aliases: [],
    notes: 'D A D E',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,2,'1'],[2,3,'3'],[1,'o']] },
  { name: 'Dsus4', families: ['sus'], aliases: [],
    notes: 'D A D G',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,2,'1'],[2,3,'2'],[1,3,'3']] },
  { name: 'Asus2', families: ['sus'], aliases: [],
    notes: 'A E A B E',
    fingers: [[6,'x'],[5,'o'],[4,2,'1'],[3,2,'2'],[2,'o'],[1,'o']] },
  { name: 'Asus4', families: ['sus'], aliases: [],
    notes: 'A E A D E',
    fingers: [[6,'x'],[5,'o'],[4,2,'1'],[3,2,'2'],[2,3,'3'],[1,'o']] },
  { name: 'Fsus4', families: ['sus'], aliases: [],
    notes: 'F C F A♯ C F', position: 1, barres: [{fromString:6,toString:1,fret:1}],
    fingers: [[5,3,'2'],[4,3,'3'],[3,3,'4']] },
  { name: 'Fsus2', families: ['sus'], aliases: [],
    notes: 'F C F G C', position: 8, barres: [{fromString:5,toString:1,fret:8}],
    fingers: [[6,'x'],[4,10,'2'],[3,10,'3']] },
  { name: 'F♯sus4', families: ['sus'], aliases: ['G♭sus4'],
    notes: 'F♯ C♯ F♯ B C♯ F♯', position: 1, barres: [{fromString:6,toString:1,fret:2}],
    fingers: [[5,4,'2'],[4,4,'3'],[3,4,'4']] },
  { name: 'F♯sus2', families: ['sus'], aliases: ['G♭sus2'],
    notes: 'F♯ C♯ F♯ G♯ C♯', position: 9, barres: [{fromString:5,toString:1,fret:9}],
    fingers: [[6,'x'],[4,11,'2'],[3,11,'3']] },
  { name: 'Gsus4', families: ['sus'], aliases: [],
    notes: 'G D G C D G', position: 1, barres: [{fromString:6,toString:1,fret:3}],
    fingers: [[5,5,'2'],[4,5,'3'],[3,5,'4']] },
  { name: 'Gsus2', families: ['sus'], aliases: [],
    notes: 'G D G A D', position: 10, barres: [{fromString:5,toString:1,fret:10}],
    fingers: [[6,'x'],[4,12,'2'],[3,12,'3']] },
  { name: 'A♭sus4', families: ['sus'], aliases: ['G♯sus4'],
    notes: 'A♭ E♭ A♭ D♭ E♭ A♭', position: 4, barres: [{fromString:6,toString:1,fret:4}],
    fingers: [[5,6,'2'],[4,6,'3'],[3,6,'4']] },
  { name: 'A♭sus2', families: ['sus'], aliases: ['G♯sus2'],
    notes: 'A♭ E♭ A♭ B♭ E♭', position: 11, barres: [{fromString:5,toString:1,fret:11}],
    fingers: [[6,'x'],[4,13,'2'],[3,13,'3']] },
  { name: 'B♭sus4', families: ['sus'], aliases: ['A♯sus4'],
    notes: 'B♭ F B♭ E♭ F', position: 1, barres: [{fromString:5,toString:1,fret:1}],
    fingers: [[6,'x'],[4,3,'2'],[3,3,'3'],[2,4,'4']] },
  { name: 'B♭sus2', families: ['sus'], aliases: ['A♯sus2'],
    notes: 'B♭ F B♭ C F', position: 1, barres: [{fromString:5,toString:1,fret:1}],
    fingers: [[6,'x'],[4,3,'2'],[3,3,'3']] },
  { name: 'Bsus4', families: ['sus'], aliases: [],
    notes: 'B F♯ B E F♯', position: 1, barres: [{fromString:5,toString:1,fret:2}],
    fingers: [[6,'x'],[4,4,'2'],[3,4,'3'],[2,5,'4']] },
  { name: 'Bsus2', families: ['sus'], aliases: [],
    notes: 'B F♯ B C♯ F♯', position: 1, barres: [{fromString:5,toString:1,fret:2}],
    fingers: [[6,'x'],[4,4,'2'],[3,4,'3']] },
  { name: 'D♭sus4', families: ['sus'], aliases: ['C♯sus4'],
    notes: 'D♭ A♭ D♭ G♭ A♭', position: 4, barres: [{fromString:5,toString:1,fret:4}],
    fingers: [[6,'x'],[4,6,'2'],[3,6,'3'],[2,7,'4']] },
  { name: 'D♭sus2', families: ['sus'], aliases: ['C♯sus2'],
    notes: 'D♭ A♭ D♭ E♭ A♭', position: 4, barres: [{fromString:5,toString:1,fret:4}],
    fingers: [[6,'x'],[4,6,'2'],[3,6,'3']] },
  { name: 'E♭sus4', families: ['sus'], aliases: ['D♯sus4'],
    notes: 'E♭ B♭ E♭ A♭ B♭', position: 6, barres: [{fromString:5,toString:1,fret:6}],
    fingers: [[6,'x'],[4,8,'2'],[3,8,'3'],[2,9,'4']] },
  { name: 'E♭sus2', families: ['sus'], aliases: ['D♯sus2'],
    notes: 'E♭ B♭ E♭ F B♭', position: 6, barres: [{fromString:5,toString:1,fret:6}],
    fingers: [[6,'x'],[4,8,'2'],[3,8,'3']] },
  { name: 'Csus4', families: ['sus'], aliases: [],
    notes: 'C G C F G', position: 3, barres: [{fromString:5,toString:1,fret:3}],
    fingers: [[6,'x'],[4,5,'2'],[3,5,'3'],[2,6,'4']] },
  { name: 'Csus2', families: ['sus'], aliases: [],
    notes: 'C G C D G', position: 1, barres: [{fromString:5,toString:1,fret:3}],
    fingers: [[6,'x'],[4,5,'2'],[3,5,'3']] },
  { name: 'Esus4', families: ['sus'], aliases: [],
    notes: 'E B E A B E',
    fingers: [[6,'o'],[5,2,'2'],[4,2,'3'],[3,2,'4'],[2,'o'],[1,'o']] },
  { name: 'Esus2', families: ['sus'], aliases: [],
    notes: 'E B F♯ B E',
    fingers: [[6,'o'],[5,2,'1'],[4,4,'3'],[3,4,'4'],[2,'o'],[1,'o']] },

  // ----- SEXTAS (6) -----
  { name: 'C6', families: ['6ta'], aliases: [],
    notes: 'C E A C E',
    fingers: [[6,'x'],[5,3,'4'],[4,2,'3'],[3,2,'2'],[2,1,'1'],[1,'o']] },
  { name: 'D6', families: ['6ta'], aliases: [],
    notes: 'D A B F♯',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,2,'1'],[2,'o'],[1,2,'2']] },
  { name: 'E6', families: ['6ta'], aliases: [],
    notes: 'E B E G♯ C♯ E',
    fingers: [[6,'o'],[5,2,'2'],[4,2,'3'],[3,1,'1'],[2,2,'4'],[1,'o']] },
  { name: 'G6', families: ['6ta'], aliases: [],
    notes: 'G B D G B E',
    fingers: [[6,3,'2'],[5,2,'1'],[4,'o'],[3,'o'],[2,'o'],[1,'o']] },
  { name: 'A6', families: ['6ta'], aliases: [],
    notes: 'A E A C♯ F♯', barres: [{fromString:4,toString:1,fret:2}],
    fingers: [[6,'x'],[5,'o']] },
  { name: 'F6', families: ['6ta'], aliases: [],
    notes: 'F A D F',
    fingers: [[6,'x'],[5,'x'],[4,3,'3'],[3,2,'2'],[2,3,'4'],[1,1,'1']] },
  { name: 'F♯6', families: ['6ta'], aliases: ['G♭6'],
    notes: 'F♯ A♯ D♯ F♯', position: 2,
    fingers: [[6,'x'],[5,'x'],[4,4,'3'],[3,3,'2'],[2,4,'4'],[1,2,'1']] },
  { name: 'A♭6', families: ['6ta'], aliases: ['G♯6'],
    notes: 'A♭ C F A♭', position: 4,
    fingers: [[6,'x'],[5,'x'],[4,6,'3'],[3,5,'2'],[2,6,'4'],[1,4,'1']] },
  { name: 'B♭6', families: ['6ta'], aliases: ['A♯6'],
    notes: 'B♭ F B♭ D G', position: 1, barres: [{fromString:4,toString:1,fret:3}],
    fingers: [[6,'x'],[5,1,'1']] },
  { name: 'B6', families: ['6ta'], aliases: [],
    notes: 'B F♯ B D♯ G♯', position: 2, barres: [{fromString:4,toString:1,fret:4}],
    fingers: [[6,'x'],[5,2,'1']] },
  { name: 'D♭6', families: ['6ta'], aliases: ['C♯6'],
    notes: 'D♭ A♭ D♭ F B♭', position: 4, barres: [{fromString:4,toString:1,fret:6}],
    fingers: [[6,'x'],[5,4,'1']] },
  { name: 'E♭6', families: ['6ta'], aliases: ['D♯6'],
    notes: 'E♭ B♭ E♭ G C', position: 6, barres: [{fromString:4,toString:1,fret:8}],
    fingers: [[6,'x'],[5,6,'1']] },

  // ----- NOVENAS MAYORES (maj9) -----
  { name: 'Cmaj9', families: ['maj9'], aliases: ['CM9','CΔ9'],
    notes: 'C E B D',
    fingers: [[6,'x'],[5,3,'2'],[4,2,'1'],[3,4,'4'],[2,3,'3'],[1,'x']] },
  { name: 'Dmaj9', families: ['maj9'], aliases: ['DM9','DΔ9'], position: 4,
    notes: 'D F♯ C♯ E',
    fingers: [[6,'x'],[5,5,'2'],[4,4,'1'],[3,6,'4'],[2,5,'3'],[1,'x']] },
  { name: 'Emaj9', families: ['maj9'], aliases: ['EM9','EΔ9'], position: 6,
    notes: 'E G♯ D♯ F♯',
    fingers: [[6,'x'],[5,7,'2'],[4,6,'1'],[3,8,'4'],[2,7,'3'],[1,'x']] },
  { name: 'Gmaj9', families: ['maj9'], aliases: ['GM9','GΔ9'], position: 9,
    notes: 'G B F♯ A',
    fingers: [[6,'x'],[5,10,'2'],[4,9,'1'],[3,11,'4'],[2,10,'3'],[1,'x']] },
  { name: 'Amaj9', families: ['maj9'], aliases: ['AM9','AΔ9'], position: 4,
    notes: 'A C♯ G♯ B',
    fingers: [[6,5,'3'],[5,4,'1'],[4,6,'4'],[3,4,'2'],[2,'x'],[1,'x']] },
  { name: 'Fmaj9', families: ['maj9'], aliases: ['FM9','FΔ9'], position: 7,
    notes: 'F A E G',
    fingers: [[6,'x'],[5,8,'2'],[4,7,'1'],[3,9,'4'],[2,8,'3'],[1,'x']] },
  { name: 'F♯maj9', families: ['maj9'], aliases: ['G♭maj9'], position: 8,
    notes: 'F♯ A♯ F G♯',
    fingers: [[6,'x'],[5,9,'2'],[4,8,'1'],[3,10,'4'],[2,9,'3'],[1,'x']] },
  { name: 'A♭maj9', families: ['maj9'], aliases: ['G♯maj9'], position: 10,
    notes: 'A♭ C G B♭',
    fingers: [[6,'x'],[5,11,'2'],[4,10,'1'],[3,12,'4'],[2,11,'3'],[1,'x']] },
  { name: 'B♭maj9', families: ['maj9'], aliases: ['A♯maj9'],
    notes: 'B♭ D F C',
    fingers: [[6,'x'],[5,1,'1'],[4,'o'],[3,2,'3'],[2,1,'2'],[1,'x']] },
  { name: 'Bmaj9', families: ['maj9'], aliases: [],
    notes: 'B D♯ A♯ C♯',
    fingers: [[6,'x'],[5,2,'2'],[4,1,'1'],[3,3,'4'],[2,2,'3'],[1,'x']] },
  { name: 'D♭maj9', families: ['maj9'], aliases: ['C♯maj9'], position: 3,
    notes: 'D♭ F C E♭',
    fingers: [[6,'x'],[5,4,'2'],[4,3,'1'],[3,5,'4'],[2,4,'3'],[1,'x']] },
  { name: 'E♭maj9', families: ['maj9'], aliases: ['D♯maj9'], position: 5,
    notes: 'E♭ G D F',
    fingers: [[6,'x'],[5,6,'2'],[4,5,'1'],[3,7,'4'],[2,6,'3'],[1,'x']] },

  // ----- SLASH (bajo invertido) -----
  { name: 'D/F#', families: ['slash'], aliases: ['D/F♯'],
    notes: 'F♯ D F♯ A D',
    fingers: [[6,2,'1'],[5,'x'],[4,'o'],[3,2,'2'],[2,3,'4'],[1,2,'3']] },
  { name: 'C/G', families: ['slash'], aliases: [],
    notes: 'G C E G C E',
    fingers: [[6,3,'3'],[5,3,'4'],[4,2,'2'],[3,'o'],[2,1,'1'],[1,'o']] },
  { name: 'G/B', families: ['slash'], aliases: [],
    notes: 'B D G B G',
    fingers: [[6,'x'],[5,2,'1'],[4,'o'],[3,'o'],[2,3,'3'],[1,3,'4']] },
  { name: 'F/E', families: ['slash'], aliases: [],
    notes: 'E F A C F',
    fingers: [[6,'o'],[5,'x'],[4,3,'3'],[3,2,'2'],[2,1,'1'],[1,1,'1']] },
  { name: 'C/E', families: ['slash'], aliases: [],
    notes: 'E C E G C E',
    fingers: [[6,'o'],[5,3,'3'],[4,2,'2'],[3,'o'],[2,1,'1'],[1,'o']] },
  { name: 'D/A', families: ['slash'], aliases: [],
    notes: 'A D A D F♯',
    fingers: [[6,'x'],[5,'o'],[4,'o'],[3,2,'1'],[2,3,'3'],[1,2,'2']] },
  { name: 'A/E', families: ['slash'], aliases: [],
    notes: 'E A E A C♯ E',
    fingers: [[6,'o'],[5,'o'],[4,2,'1'],[3,2,'2'],[2,2,'3'],[1,'o']] },
  { name: 'A/C#', families: ['slash'], aliases: ['A/C♯'],
    notes: 'C♯ E A C♯ E',
    fingers: [[6,'x'],[5,4,'3'],[4,2,'1'],[3,2,'1'],[2,2,'1'],[1,'o']] },
  { name: 'E/G#', families: ['slash'], aliases: ['E/G♯'],
    notes: 'G♯ B E G♯ B E',
    fingers: [[6,4,'4'],[5,2,'2'],[4,2,'3'],[3,1,'1'],[2,'o'],[1,'o']] },
  { name: 'F/A', families: ['slash'], aliases: [],
    notes: 'A F A C F',
    fingers: [[6,'x'],[5,'o'],[4,3,'3'],[3,2,'2'],[2,1,'1'],[1,1,'1']] },
  { name: 'G/D', families: ['slash'], aliases: [],
    notes: 'D G B G',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,'o'],[2,'o'],[1,3,'3']] },
  { name: 'G/A', families: ['slash'], aliases: ['A11'],
    notes: 'A D G B G',
    fingers: [[6,'x'],[5,'o'],[4,'o'],[3,'o'],[2,'o'],[1,3,'3']] },
  { name: 'G7/B', families: ['slash'], aliases: [],
    notes: 'B D G B F',
    fingers: [[6,'x'],[5,2,'2'],[4,'o'],[3,'o'],[2,'o'],[1,1,'1']] },
  { name: 'Am/G', families: ['slash'], aliases: [],
    notes: 'G A E A C E',
    fingers: [[6,3,'4'],[5,'o'],[4,2,'2'],[3,2,'3'],[2,1,'1'],[1,'o']] },
  { name: 'Am/F#', families: ['slash'], aliases: ['Am/F♯','F♯m7♭5'],
    notes: 'F♯ A E A C E',
    fingers: [[6,2,'2'],[5,'o'],[4,2,'3'],[3,2,'4'],[2,1,'1'],[1,'o']] },
  { name: 'D/C', families: ['slash'], aliases: [],
    notes: 'C D A D F♯',
    fingers: [[6,'x'],[5,3,'3'],[4,'o'],[3,2,'1'],[2,3,'4'],[1,2,'2']] },

  // ----- OTROS (dim7, aug, semidisminuido, tensiones) -----
  { name: 'Bm7b5', families: ['otros'], aliases: ['Bø','Bm7(♭5)','B-7b5'],
    notes: 'B F A D',
    fingers: [[6,'x'],[5,2,'1'],[4,3,'3'],[3,2,'2'],[2,3,'4'],[1,'x']] },
  { name: 'Caug', families: ['otros'], aliases: ['C+','C(#5)'],
    notes: 'C E G♯ C E',
    fingers: [[6,'x'],[5,3,'4'],[4,2,'3'],[3,1,'1'],[2,1,'2'],[1,'o']] },
  { name: 'Em(add9)', families: ['otros'], aliases: ['Em9 (sin 7)'],
    notes: 'E B E G B F♯',
    fingers: [[6,'o'],[5,2,'2'],[4,2,'3'],[3,'o'],[2,'o'],[1,2,'4']] },
  { name: 'Cdim7', families: ['otros'], aliases: ['C°7','Cdim','C°'],
    notes: 'C F♯ A D♯', position: 10, barres: [],
    fingers: [[6,'x'],[5,'x'],[4,10,'1'],[3,11,'2'],[2,10,'1'],[1,11,'3']] },
  { name: 'D♭dim7', families: ['otros'], aliases: ['D♭°7','D♭dim','D♭°','C♯dim7','C♯°7'],
    notes: 'D♭ G B♭ E', position: 11, barres: [],
    fingers: [[6,'x'],[5,'x'],[4,11,'1'],[3,12,'2'],[2,11,'1'],[1,12,'3']] },
  { name: 'Ddim7', families: ['otros'], aliases: ['D°7','Ddim','D°'],
    notes: 'D G♯ B F',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,1,'2'],[2,'o'],[1,1,'3']] },
  { name: 'E♭dim7', families: ['otros'], aliases: ['E♭°7','E♭dim','E♭°','D♯dim7','D♯°7'],
    notes: 'E♭ A C G♭',
    fingers: [[6,'x'],[5,'x'],[4,1,'1'],[3,2,'2'],[2,1,'1'],[1,2,'3']] },
  { name: 'Edim7', families: ['otros'], aliases: ['E°7','Edim','E°'],
    notes: 'E A♯ C♯ G',
    fingers: [[6,'x'],[5,'x'],[4,2,'1'],[3,3,'2'],[2,2,'1'],[1,3,'3']] },
  { name: 'Fdim7', families: ['otros'], aliases: ['F°7','Fdim','F°'],
    notes: 'F B D G♯',
    fingers: [[6,'x'],[5,'x'],[4,3,'1'],[3,4,'2'],[2,3,'1'],[1,4,'3']] },
  { name: 'F♯dim7', families: ['otros'], aliases: ['F♯°7','F♯dim','F♯°','G♭dim7','G♭°7'],
    notes: 'F♯ C D♯ A',
    fingers: [[6,'x'],[5,'x'],[4,4,'1'],[3,5,'2'],[2,4,'1'],[1,5,'3']] },
  { name: 'Gdim7', families: ['otros'], aliases: ['G°7','Gdim','G°'],
    notes: 'G C♯ E A♯', position: 5, barres: [],
    fingers: [[6,'x'],[5,'x'],[4,5,'1'],[3,6,'2'],[2,5,'1'],[1,6,'3']] },
  { name: 'A♭dim7', families: ['otros'], aliases: ['A♭°7','A♭dim','A♭°','G♯dim7','G♯°7'],
    notes: 'A♭ D F B', position: 6, barres: [],
    fingers: [[6,'x'],[5,'x'],[4,6,'1'],[3,7,'2'],[2,6,'1'],[1,7,'3']] },
  { name: 'Adim7', families: ['otros'], aliases: ['A°7','Adim','A°'],
    notes: 'A D♯ F♯ C', position: 7, barres: [],
    fingers: [[6,'x'],[5,'x'],[4,7,'1'],[3,8,'2'],[2,7,'1'],[1,8,'3']] },
  { name: 'B♭dim7', families: ['otros'], aliases: ['B♭°7','B♭dim','B♭°','A♯dim7','A♯°7'],
    notes: 'B♭ E G D♭', position: 8, barres: [],
    fingers: [[6,'x'],[5,'x'],[4,8,'1'],[3,9,'2'],[2,8,'1'],[1,9,'3']] },
  { name: 'Bdim7', families: ['otros'], aliases: ['B°7','Bdim','B°'],
    notes: 'B F G♯ D', position: 9, barres: [],
    fingers: [[6,'x'],[5,'x'],[4,9,'1'],[3,10,'2'],[2,9,'1'],[1,10,'3']] },
  { name: 'Eaug', families: ['otros'], aliases: ['E+','E(♯5)'],
    notes: 'E C E G♯ C E',
    fingers: [[6,'o'],[5,3,'3'],[4,2,'2'],[3,1,'1'],[2,1,'1'],[1,'o']] },
  { name: 'Aaug', families: ['otros'], aliases: ['A+','A(♯5)'],
    notes: 'A F A C♯ F',
    fingers: [[6,'x'],[5,'o'],[4,3,'3'],[3,2,'2'],[2,2,'2'],[1,1,'1']] },
  { name: 'Daug', families: ['otros'], aliases: ['D+','D(♯5)'],
    notes: 'D A♯ D F♯',
    fingers: [[6,'x'],[5,'x'],[4,'o'],[3,3,'3'],[2,3,'4'],[1,2,'1']] },
  { name: 'Gaug', families: ['otros'], aliases: ['G+','G(♯5)'],
    notes: 'G B D♯ G B G',
    fingers: [[6,3,'3'],[5,2,'2'],[4,1,'1'],[3,'o'],[2,'o'],[1,3,'4']] },
  { name: 'Faug', families: ['otros'], aliases: ['F+','F(♯5)'],
    notes: 'F A C♯ F',
    fingers: [[6,'x'],[5,'x'],[4,3,'3'],[3,2,'2'],[2,2,'2'],[1,1,'1']] },

];
